version: '3.8'

services:
  backend:
    image: vault-backend
    build: 
      context: ./backend
    depends_on:
      - mysql
    networks: 
      - backend

  mysql:
    image: mysql:8.0.17
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: Lsy3Y942@vqU
      MYSQL_DATABASE: vault
    ports:
      - "3309:3306"  # Remove EXPOSE in production
    networks: 
      - backend
    cap_add:
      - SYS_NICE  

  frontend:
    image: vault-frontend
    build:
      context: ./frontend
    depends_on:
      - backend
    networks:
      - backend

  proxy:
    image: vault-nginx-reverse
    build:
      context: ./nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    networks: 
      - frontend
      - backend
    healthcheck:
        test: ["CMD", "wget", "-qO-", "http://frontend:3000"]
        interval: 5s
        timeout: 10s
        retries: 100

networks: 
  frontend:
  backend: