version: '3.8'

services:
  backend:
    image: vault-backend:0.0.1
    build: 
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks: 
      - backend

  mysql:
    image: mysql:8.0.17
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: Lsy3Y942@vqU
      MYSQL_DATABASE: vault
    ports:
      - "3309:3306"  # Remove EXPOSE in production
    networks: 
      - backend
    cap_add:
      - SYS_NICE  

networks: 
  backend: